-- DECIXN | Supabase Master Schema
-- This script contains all tables, functions, triggers, and RLS policies for the DECIXN platform.
-- Copy and paste this into the Supabase SQL Editor to initialize your database.

-- ==========================================
-- 1. EXTENSIONS & INITIAL SETUP
-- ==========================================
CREATE EXTENSION IF NOT EXISTS "pg_random_uuid";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- ==========================================
-- 2. CORE AUTH & USER PROFILES
-- ==========================================
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Handle New User Trigger
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, email)
  VALUES (new.id, new.email);
  RETURN new;
END;
$$;

-- Drop trigger if exists before creating
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW
EXECUTE PROCEDURE public.handle_new_user();

-- ==========================================
-- 3. STOCK ASSETS (Watchlists & Portfolio)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.watchlists (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.watchlist_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  watchlist_id UUID REFERENCES public.watchlists(id) ON DELETE CASCADE,
  symbol TEXT NOT NULL,
  added_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (watchlist_id, symbol)
);

-- ==========================================
-- 4. MUTUAL FUND ECOSYSTEM
-- ==========================================
CREATE TABLE IF NOT EXISTS public.mf_schemes (
  scheme_code TEXT PRIMARY KEY,
  scheme_name TEXT NOT NULL,
  isin_div_payout TEXT,
  isin_reinvest TEXT,
  scheme_category TEXT,
  scheme_type TEXT,
  amc_name TEXT,
  last_updated TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_mf_schemes_name ON public.mf_schemes USING GIN (scheme_name gin_trgm_ops);

CREATE TABLE IF NOT EXISTS public.mf_nav_history (
  scheme_code TEXT REFERENCES public.mf_schemes(scheme_code) ON DELETE CASCADE,
  nav DECIMAL(15, 4) NOT NULL,
  nav_date DATE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (scheme_code, nav_date)
);

CREATE INDEX IF NOT EXISTS idx_mf_nav_history_date ON public.mf_nav_history (nav_date DESC);

-- Fuzzy Search Function for Mutual Funds
CREATE OR REPLACE FUNCTION public.search_mf_fuzzy(search_term TEXT)
RETURNS SETOF public.mf_schemes AS $$
DECLARE
  normalized_term TEXT;
BEGIN
  normalized_term := REPLACE(search_term, ' ', '');
  
  RETURN QUERY
  SELECT *
  FROM public.mf_schemes
  WHERE 
    scheme_name % search_term 
    OR REPLACE(scheme_name, ' ', '') % normalized_term 
  ORDER BY 
    GREATEST(
      similarity(scheme_name, search_term), 
      similarity(REPLACE(scheme_name, ' ', ''), normalized_term)
    ) DESC
  LIMIT 10;
END;
$$ LANGUAGE plpgsql;

-- ==========================================
-- 5. INTELLIGENCE & NEWS (Catalyst Engine)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.news (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT,
  summary TEXT,
  source TEXT,
  url TEXT,
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  sentiment TEXT, -- positive / negative / neutral
  impact_summary TEXT, -- generated by Gemini
  event_type TEXT DEFAULT 'other',
  impact_strength INTEGER DEFAULT 1,
  raw_json JSONB
);

CREATE TABLE IF NOT EXISTS public.news_stocks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  news_id UUID REFERENCES public.news(id) ON DELETE CASCADE,
  symbol TEXT NOT NULL,
  impact TEXT, -- bullish / bearish / neutral
  relevance_score FLOAT DEFAULT 0.0,
  UNIQUE (news_id, symbol)
);

CREATE TABLE IF NOT EXISTS public.news_sectors (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  news_id UUID REFERENCES public.news(id) ON DELETE CASCADE,
  sector TEXT,
  impact TEXT
);

-- ==========================================
-- 6. RISK & MONITORING (Alerts & Notifications)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.alerts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  symbol TEXT NOT NULL,
  condition JSONB NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  is_triggered BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  triggered_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  title TEXT,
  message TEXT,
  is_read BOOLEAN DEFAULT FALSE,
  type TEXT DEFAULT 'ALERT',
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 7. CHAT & MESSAGE HISTORY (Foxy Assistant)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.chat_history (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    session_id UUID NOT NULL DEFAULT gen_random_uuid(),
    role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
    content TEXT NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for Chat
ALTER TABLE public.chat_history ENABLE ROW LEVEL SECURITY;

-- Chat RLS Policies
DROP POLICY IF EXISTS "Users can view their own chat history" ON public.chat_history;
CREATE POLICY "Users can view their own chat history"
    ON public.chat_history FOR SELECT
    USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own chat history" ON public.chat_history;
CREATE POLICY "Users can insert their own chat history"
    ON public.chat_history FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- Performance Indexes
CREATE INDEX IF NOT EXISTS idx_chat_history_user_id ON public.chat_history(user_id);
CREATE INDEX IF NOT EXISTS idx_chat_history_session_id ON public.chat_history(session_id);
CREATE INDEX IF NOT EXISTS idx_chat_history_created_at ON public.chat_history(created_at);

-- ==========================================
-- 8. EXTRA RLS & PERMISSIONS
-- ==========================================
ALTER TABLE public.mf_schemes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mf_nav_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access for mf_schemes" ON public.mf_schemes;
CREATE POLICY "Allow public read access for mf_schemes" ON public.mf_schemes FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read access for mf_nav_history" ON public.mf_nav_history;
CREATE POLICY "Allow public read access for mf_nav_history" ON public.mf_nav_history FOR SELECT USING (true);
